name: Deploy backend to VM
on:
    pull_request:
        branches:
        - 'main'
    push:
        branches:
        - 'main'

jobs:
  deploy:
    if: "!startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        env:
            GITHUB_ACTOR: ${{ github.github_actor }}
            BRANCH: ${{ github.ref_name }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          envs: GITHUB_ACTOR,BRANCH
          script: |
            TIMESTAMP=$(date +%Y%m%d_%H%M)
            mkdir -p /home/vagrant/test-ci/test-$TIMESTAMP-$GITHUB_ACTOR 
            cd /home/vagrant/test-ci/test-$TIMESTAMP-$GITHUB_ACTOR 
            gh repo clone https://github.com/DominicHoang/nx-node-fastify-example.git -- --branch $BRANCH
            cd nx-node-fastify-example
            /usr/bin/yarn install 
            /usr/bin/yarn nx run-many --target=build --projects=fastify-app
            RANDOM_PORT="$(shuf -i 3300-3400 -n 1)"
            echo $RANDOM_PORT
            echo "/usr/bin/yarn nx run fastify-app:serve:production --port=$RANDOM_PORT" > run.sh
            chmod +x run.sh
            nohup ./run.sh &
